// actions/types.js
export const SET_PERSONAL_INFO = 'SET_PERSONAL_INFO';
export const SET_CAR_INFO = 'SET_CAR_INFO';
export const SET_VEHICLE_INFO = 'SET_VEHICLE_INFO';
export const SET_ADDRESS_INFO = 'SET_ADDRESS_INFO';
export const SET_BRAND_INFO = 'SET_BRAND_INFO';
export const SET_STICKER_INFO = 'SET_STICKER_INFO';


export const RESET_PERSONAL_INFO = 'RESET_PERSONAL_INFO';
export const RESET_CAR_INFO = 'RESET_CAR_INFO';
export const RESET_VEHICLE_INFO = 'RESET_VEHICLE_INFO';
export const RESET_ADDRESS_INFO = 'RESET_ADDRESS_INFO';
export const RESET_BRAND_INFO = 'RESET_BRAND_INFO';
export const RESET_STICKER_INFO = 'RESET_STICKER_INFO';